// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXgUKwvhvVSkLnpWJ2eqSD6XvPyTeDyRs',
    appId: '1:668500445402:web:82fc2e49fce82f36c23de3',
    messagingSenderId: '668500445402',
    projectId: 'todo-5bd84',
    authDomain: 'todo-5bd84.firebaseapp.com',
    storageBucket: 'todo-5bd84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXbrw9E4E1WBxYxqo6X_bNAy2OmtEd1m4',
    appId: '1:668500445402:android:4e28a761899b9be3c23de3',
    messagingSenderId: '668500445402',
    projectId: 'todo-5bd84',
    storageBucket: 'todo-5bd84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgf2YAN5RP7LFviUPyYANyUgT7AzEKCeU',
    appId: '1:668500445402:ios:6441b5da752b3981c23de3',
    messagingSenderId: '668500445402',
    projectId: 'todo-5bd84',
    storageBucket: 'todo-5bd84.appspot.com',
    iosClientId: '668500445402-03486ia704ekin8rclqnlmc5f1kfgi0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
